### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by a-turcu** [pluskal-lab/DreaMS#7]
Hello,

The following links don't work:
https://zenodo.org/record/TODO
https://huggingface.co/roman-bushuiev/GeMS

Additionally, running the example code:
from dreams.api import dreams_embeddings
embs = dreams_embeddings('data/examples/example_5_spectra.mgf')

Results in:

Traceback (most recent call last):
  File "c:\Users\alexa\Documents\Projects\novogaia\test.py", line 7, in <module>
    embs = dreams_embeddings('data/examples/example_5_spectra.mgf')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\alexa\documents\projects\novogaia\dreams\dreams\api.py", line 162, in dreams_embeddings
    return dreams_predictions(
           ^^^^^^^^^^^^^^^^^^^
  File "c:\users\alexa\documents\projects\novogaia\dreams\dreams\api.py", line 98, in dreams_predictions
    model_ckpt = PreTrainedModel.from_name(model_ckpt)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\alexa\documents\projects\novogaia\dreams\dreams\api.py", line 69, in from_name
    utils.download_pretrained_model(ckpt_path)
  File "c:\users\alexa\documents\projects\novogaia\dreams\dreams\utils\misc.py", line 16, in download_pretrained_model
    url = 'https://zenodo.org/records/10997887/files/' + model_name
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
TypeError: can only concatenate str (not "WindowsPath") to str

**Comment by roman-bushuiev** [comment]
Hi! Thank you for checking it out. I have fixed the broken links and model downloading when running the example code.

Please let me know if you encounter any other issues!
